# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 187221bd723e11ec2549c846df82aed42f09acffe8026a20744251b21441e5183ab3b5da802b2470b568b78f32356dea6c705f7453e6a83d92f7c570f1e7d888

test:
  secret_key_base: 905852191e9d7352fbd2bca3cafb1d7fd0085f49324c754aa60c951c4fb47f97928b36c5a524789d5e790d8628b789f356c3efae0cf822423ceaa75fd4407eb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
